import { createRuntimeServices } from './runtime.js';
import { installConstants } from './constants.js';
import { installState } from './state.js';
import { installTextUtilities } from './text-utils.js';
import { installAppHelpers } from './app-helpers.js';
import { installPreferences } from './preferences.js';
import { installConnectionUi } from './ui-connection.js';
import { installCreateUi } from './ui-create.js';
import { installScriptUi } from './ui-script.js';
import { installScriptValidation } from './script-validation.js';
import { installGeminiTransport } from './gemini-api.js';
import { installScriptGeneration } from './script-generation.js';
import { installPcmAudio } from './pcm-audio.js';
import { installWavEncoder } from './wav-encoder.js';
import { installTtsChunking } from './tts-chunking.js';
import { installTtsTransport } from './tts-generation.js';
import { installGenerationJobs } from './generation-jobs.js';
import { installAudioUi } from './ui-audio.js';
import { installStatusUi } from './ui-status.js';
import { installUiEvents } from './ui-events.js';
import { installIndexedDb } from './indexeddb.js';
import { installMediaCache } from './media-cache.js';
import { installVoicePreview } from './voice-preview.js';
import { installConversationPreview } from './conversation-preview.js';
import { installFinalReview } from './final-review.js';

const services = createRuntimeServices();
installConstants(services);
installState(services);
installTextUtilities(services);
installAppHelpers(services);
installPreferences(services);
installConnectionUi(services);
installCreateUi(services);
installScriptUi(services);
installScriptValidation(services);
installGeminiTransport(services);
installScriptGeneration(services);
installPcmAudio(services);
installWavEncoder(services);
installTtsChunking(services);
installTtsTransport(services);
installGenerationJobs(services);
installAudioUi(services);
installStatusUi(services);
installUiEvents(services);
installIndexedDb(services);
installMediaCache(services);
installVoicePreview(services);
installConversationPreview(services);
services.initialiseApp();
installFinalReview(services);

export { services };
