import { createAppContext } from './app-context.js';
import { installConstants } from './constants.js';
import { installState } from './state.js';
import { installTextUtils } from './text-utils.js';
import { installPreferences } from './preferences.js';
import { installPcmAudio } from './pcm-audio.js';
import { installWavEncoder } from './wav-encoder.js';
import { installDiagnostics } from './diagnostics.js';
import { installGeminiErrors } from './gemini-errors.js';
import { installUiConnection } from './ui-connection.js';
import { installUiCreate } from './ui-create.js';
import { installUiScript } from './ui-script.js';
import { installScriptValidation } from './script-validation.js';
import { installGeminiApi } from './gemini-api.js';
import { installTtsChunking } from './tts-chunking.js';
import { installTtsGeneration } from './tts-generation.js';
import { installUiAudio } from './ui-audio.js';
import { installUiStatus } from './ui-status.js';
import { installScriptGeneration } from './script-generation.js';
import { installUiEvents } from './ui-events.js';
import { installIndexeddb } from './indexeddb.js';
import { installMediaCache } from './media-cache.js';
import { installVoicePreview } from './voice-preview.js';
import { installConversationPreview } from './conversation-preview.js';
import { installFinalReview } from './final-review.js';

export const app = createAppContext();

installConstants(app);
installState(app);
installTextUtils(app);
installPreferences(app);
installPcmAudio(app);
installWavEncoder(app);
installDiagnostics(app);
installGeminiErrors(app);
installUiConnection(app);
installUiCreate(app);
installUiScript(app);
installScriptValidation(app);
installGeminiApi(app);
installTtsChunking(app);
installTtsGeneration(app);
installUiAudio(app);
installUiStatus(app);
installScriptGeneration(app);
installUiEvents(app);
installIndexeddb(app);
installMediaCache(app);
installVoicePreview(app);
installConversationPreview(app);
installFinalReview(app);
