[package]
name = "astudio-trace"
description = "A-Studio: Trace pixels to paths"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
astudio-geom = { path = "../geom" }
astudio-raster = { path = "../raster" }
astudio-vdoc = { path = "../vdoc" }

[lints]
workspace = true
